### PR TITLE
Code review request.

### PR DESCRIPTION
**Pull request by IjayAbby**
This is a replica of the Newsweek website the project consists of the following:
-Navigation bar section.
-The container/body section.
-The footer section.
-Use of Bootstrap 4.5 to achieve responsiveness of the page.

### CODE REVIEW

**Review by SafaErden — COMMENTED** [review]
## 👋 Hello **TEAM**

At fist view your page looks awesome, sadly, I can't review it because you are missing the title and sufficient description of you pull request message, details below 🔽

 ##

📝 Friendly reminder: Remember it's important to have a professional repo so you can increase your job opportunities.
Please take a step back and read the lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.

Sadly, for now, your review has been marked as invalid because of the following reasons:

You are missing the title of your PR.
You are missing a short summary of your changes in the pull request.
For next commits, remember to write your commits more descriptive.

Once you correct this, please submit a new code review and we will be glad to check it :)


⚠️ Status: Your project has been marked as invalid for now ⚠️
➡️ Please request another review once you are ready 📝

Questions or comments? Reach me on ([Twitter](https://twitter.com/safaerden)) or ([LinkedIn](https://www.linkedin.com/in/safaerden/)) 🗨️

Happy coding_ 👨‍💻 

**Safa ERDEN**

**Comment by IjayAbby** [comment]
Resubmitted the code for a review.

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- There is an extra scrollbar in the `main` section.

   image

- In `In the magazine` section, please remove this 👇 gap.

   | Source Page	| Clone Page |
   |:---:|:---:|
   |image|Annotation 2020-08-25 000912|

- In `newletter` section, the email field is overflowing 👇 .

  image

- The `subscribe` section needs to be changed in mobile screens 👇 .

   | Source Page	| Clone Page |
   |:---:|:---:|
   |image|image|

- Reduce the size of the footer logo 👇 .

   | Source Page	| Clone Page |
   |:---:|:---:|
   |image|image|

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Review by kubilaycaglayan — CHANGES_REQUESTED** [review]
Hello Team :wave: 
Status: Changes Required :recycle: 

Great job so far! :+1:  :100:  :medal_sports: 
Your website looks very good and almost the same as the original one. :star2: 
Let's make sure it is perfect by resolving some details :arrow_down: 

**In The Magazine Section**
**:camera_flash:  Screenshot **
inthemagazine

- [ ]  Please fix the breakage(one more time in the opposite direction :blush: ), the images should be in similar lines in that width.

**Subscribe Section**

**:camera_flash:  Screenshot**
subscribesection

- [ ]  Please work on the subscribe section one more time to make it accessible on the mobile view too. Currently, the button is overflowing.

:bulb:  I know these small details are not too easy to accomplish, but they are also the essence of the project.

With all my respect... :pray:

**Review by MuriloRoque — APPROVED** [review]
# Status: Approved :green_circle: 

## Hello @IjayAbby and @jrai0792 :wave: 

## Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

## You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
